-- Create inventory table
CREATE TABLE IF NOT EXISTS inventory (
    sku text PRIMARY KEY,
    barcode text,
    name text,
    quantity integer DEFAULT 0,
    image_url text,
    intake_price numeric(10,2) DEFAULT 0.00,
    selling_price numeric(10,2) DEFAULT 0.00,
    category text DEFAULT 'General'
);

-- Create index on barcode for fast scanner lookup
CREATE INDEX IF NOT EXISTS idx_inventory_barcode ON inventory(barcode);

-- Create sales table
CREATE TABLE IF NOT EXISTS sales (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date text,
    product_name text,
    sku text,
    intake numeric(10,2) DEFAULT 0.00,
    sold_price numeric(10,2) DEFAULT 0.00,
    profit numeric(10,2) DEFAULT 0.00,
    quantity integer DEFAULT 1,
    category text DEFAULT 'General'
);

-- Create categories table
CREATE TABLE IF NOT EXISTS categories (
    name text PRIMARY KEY
);

-- Insert default category
INSERT INTO categories (name) VALUES ('General') ON CONFLICT DO NOTHING;

-- Migration commands for existing databases:
-- ALTER TABLE inventory ADD COLUMN IF NOT EXISTS category text DEFAULT 'General';
-- ALTER TABLE inventory ADD COLUMN IF NOT EXISTS selling_price numeric(10,2) DEFAULT 0.00;
-- ALTER TABLE sales ADD COLUMN IF NOT EXISTS category text DEFAULT 'General';
-- CREATE TABLE IF NOT EXISTS categories (name text PRIMARY KEY);
-- INSERT INTO categories (name) VALUES ('General') ON CONFLICT DO NOTHING;

