-- 1. Create a parent Bills table to track checkout sessions
CREATE TABLE IF NOT EXISTS bills (
    bill_no text PRIMARY KEY,
    date text NOT NULL,
    customer_email text,
    total_amount numeric(10,2) NOT NULL,
    discount_type text DEFAULT 'none',
    discount_value numeric(10,2) DEFAULT 0.00,
    net_amount numeric(10,2) NOT NULL,
    status text DEFAULT 'completed'             -- 'completed', 'partially_refunded', 'refunded'
);

-- 2. Create a bill items table linking sold items to the parent bill
CREATE TABLE IF NOT EXISTS bill_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_no text REFERENCES bills(bill_no) ON DELETE CASCADE,
    sku text REFERENCES inventory(sku) ON DELETE RESTRICT,
    product_name text NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    original_price numeric(10,2) NOT NULL,
    discount_share numeric(10,2) DEFAULT 0.00,
    final_sold_price numeric(10,2) NOT NULL,
    intake_price numeric(10,2) DEFAULT 0.00,
    returned_quantity integer DEFAULT 0 CHECK (returned_quantity >= 0)
);

-- 3. Create a transaction audit log table for returns/exchanges
CREATE TABLE IF NOT EXISTS transaction_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_bill_no text REFERENCES bills(bill_no) ON DELETE CASCADE,
    type text NOT NULL,                         -- 'refund' or 'exchange'
    date text NOT NULL,
    items_involved jsonb NOT NULL,              -- e.g., [{"sku": "MAN-1", "qty": 1, "action": "returned"}]
    cash_delta numeric(10,2) DEFAULT 0.00
);

-- 4. Create index on parent bills for fast lookup
CREATE INDEX IF NOT EXISTS idx_bill_items_bill_no ON bill_items(bill_no);
CREATE INDEX IF NOT EXISTS idx_transaction_logs_bill ON transaction_logs(parent_bill_no);
